[package]
name = "acc"
version = "0.1.2"
authors = ["Rudolf Schmidt <info@rudolfschmidt.com>"]
edition = "2018"
license = "GPL-3.0"
description = "plaintext double-entry accounting command line tool"
keywords = ["cli", "terminal", "ledger", "accounting", "finance"]
categories = ["command-line-utilities", "parsing", "text-processing"]
repository = "https://github.com/rudolfschmidt/acc"
readme = "README.md"
include = [ "**/*.rs" ]

[lib]
name = "acc"
path = "src/lib/mod.rs"

[dependencies]
colored = "1.9.3"
num = "0.1.39"
